blank_issues_enabled: false
contact_links:
  - name: 222222222222
    url: https://blockscout.canny.io/feature-requests
    about: Request a feature or enhancement
  - name: 333333333333
    url: https://github.com/orgs/blockscout/discussions
    about: Ask questions and discuss topics with other community members
  - name: 444444444444
    url: https://discord.gg/blockscout
    about: The official Blockscout Discord community